---
deployment:
  tasks:
    - export DEPLOYPATH=/home/mulazjre/cdn.mulat.org
    - mkdir -p $DEPLOYPATH/ahmed
    - /bin/cp MulatAhmed-*.* $DEPLOYPATH/ahmed
    - /bin/cp README.md $DEPLOYPATH/ahmed
    - zip -mj ahmed.zip $DEPLOYPATH/ahmed/*
    - mv ahmed.zip $DEPLOYPATH/ahmed
    - echo "....finished........"